package com.example.ebook.model;

public class BookOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.id
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.user_id
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.stamps
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    private Double stamps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.book_id
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    private Long bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.gmt_create
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.id
     *
     * @return the value of book_order.id
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.id
     *
     * @param id the value for book_order.id
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.user_id
     *
     * @return the value of book_order.user_id
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.user_id
     *
     * @param userId the value for book_order.user_id
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.stamps
     *
     * @return the value of book_order.stamps
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public Double getStamps() {
        return stamps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.stamps
     *
     * @param stamps the value for book_order.stamps
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public void setStamps(Double stamps) {
        this.stamps = stamps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.book_id
     *
     * @return the value of book_order.book_id
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.book_id
     *
     * @param bookId the value for book_order.book_id
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.gmt_create
     *
     * @return the value of book_order.gmt_create
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.gmt_create
     *
     * @param gmtCreate the value for book_order.gmt_create
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}