package com.example.ebook.model;

public class stamp_Order extends stamp_OrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stamps_order.second_id
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    private Long secondId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stamps_order.type
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stamps_order.channel
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    private Integer channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stamps_order.money
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stamps_order.gmt_create
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stamps_order.second_id
     *
     * @return the value of stamps_order.second_id
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public Long getSecondId() {
        return secondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stamps_order.second_id
     *
     * @param secondId the value for stamps_order.second_id
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public void setSecondId(Long secondId) {
        this.secondId = secondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stamps_order.type
     *
     * @return the value of stamps_order.type
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stamps_order.type
     *
     * @param type the value for stamps_order.type
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stamps_order.channel
     *
     * @return the value of stamps_order.channel
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public Integer getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stamps_order.channel
     *
     * @param channel the value for stamps_order.channel
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stamps_order.money
     *
     * @return the value of stamps_order.money
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stamps_order.money
     *
     * @param money the value for stamps_order.money
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stamps_order.gmt_create
     *
     * @return the value of stamps_order.gmt_create
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stamps_order.gmt_create
     *
     * @param gmtCreate the value for stamps_order.gmt_create
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}