package com.example.ebook.mapper;

import com.example.ebook.model.StampOrder;
import com.example.ebook.model.StampOrderExample;
import com.example.ebook.model.StampOrderKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface StampOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Sat Mar 21 12:28:18 CST 2020
     */
    long countByExample(StampOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Sat Mar 21 12:28:18 CST 2020
     */
    int deleteByExample(StampOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Sat Mar 21 12:28:18 CST 2020
     */
    int deleteByPrimaryKey(StampOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Sat Mar 21 12:28:18 CST 2020
     */
    int insert(StampOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Sat Mar 21 12:28:18 CST 2020
     */
    int insertSelective(StampOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Sat Mar 21 12:28:18 CST 2020
     */
    List<StampOrder> selectByExampleWithRowbounds(StampOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Sat Mar 21 12:28:18 CST 2020
     */
    List<StampOrder> selectByExample(StampOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Sat Mar 21 12:28:18 CST 2020
     */
    StampOrder selectByPrimaryKey(StampOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Sat Mar 21 12:28:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") StampOrder record, @Param("example") StampOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Sat Mar 21 12:28:18 CST 2020
     */
    int updateByExample(@Param("record") StampOrder record, @Param("example") StampOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Sat Mar 21 12:28:18 CST 2020
     */
    int updateByPrimaryKeySelective(StampOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Sat Mar 21 12:28:18 CST 2020
     */
    int updateByPrimaryKey(StampOrder record);
}