package com.example.ebook.mapper;

import com.example.ebook.model.stamp_Order;
import com.example.ebook.model.stamp_OrderExample;
import com.example.ebook.model.stamp_OrderKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface stamp_OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    long countByExample(stamp_OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    int deleteByExample(stamp_OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    int deleteByPrimaryKey(stamp_OrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    int insert(stamp_Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    int insertSelective(stamp_Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    List<stamp_Order> selectByExampleWithRowbounds(stamp_OrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    List<stamp_Order> selectByExample(stamp_OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    stamp_Order selectByPrimaryKey(stamp_OrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") stamp_Order record, @Param("example") stamp_OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    int updateByExample(@Param("record") stamp_Order record, @Param("example") stamp_OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    int updateByPrimaryKeySelective(stamp_Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamps_order
     *
     * @mbg.generated Thu Mar 19 13:10:56 CST 2020
     */
    int updateByPrimaryKey(stamp_Order record);
}